### ISSUE TITLE
[Bug] Truncate is lacking precision

### ISSUE THREAD

**Issue by posidoni** [bezlant/s21_bigint#41]
```
    // ISSUE
```

https://github.com/bezlant/int128_implementation/blob/8ef711d6eb7e2f6da4c1e8c4a764a69220958b14/src/conversion/s21_from_decimal_to_int.c#L6

**Comment by bezlant** [comment]
I have reimplemented it without using floats. Will be testing it heavily today.

**Comment by bezlant** [comment]
Truncated should be fixed. Feel free to review the tests and use it!
