### ISSUE TITLE
s21_sub seems to have bugs

### ISSUE THREAD

**Issue by bezlant** [bezlant/s21_bigint#51]
I keep getting weird answers with relatively simple numbers.
I've been trying to implement round using subtraction. 
What I've been doing is 15315.513515 - 15315.000000 and getting bad results.
<img width="1132" alt="Screen Shot 2022-06-13 at 09 16 34" src="https://user-images.githubusercontent.com/89563512/173292265-453a4fef-89e3-4de2-a59b-19a6f5c5fc17.png">
<img width="1122" alt="Screen Shot 2022-06-13 at 09 19 35" src="https://user-images.githubusercontent.com/89563512/173292268-37f42174-84bb-4b5d-a6d0-31fd7940b26b.png">
<img width="1128" alt="Screen Shot 2022-06-13 at 09 22 26" src="https://user-images.githubusercontent.com/89563512/173292271-9d5f6f5a-0511-48d7-9869-2a1b13557f84.png">

**Comment by posidoni** [comment]
Totally agree. I think, today we should examine round as we did with add & maybe rewrite it. I hope, that would not be too difficult.

**Comment by posidoni** [comment]
Fixed this with #55
