### ISSUE TITLE
[CRITICAL BUG] s21_div goes into an infinite loop

### ISSUE THREAD

**Issue by bezlant** [bezlant/s21_bigint#67]
Those are the values that cause an infinite loop.
<img width="1210" alt="Screen Shot 2022-06-17 at 09 19 29" src="https://user-images.githubusercontent.com/89563512/174237487-813f269c-8f26-45d5-92f8-2010f0df8aa6.png">

**Comment by bezlant** [comment]
Tested multiple times, when the second value negative always causes an infinite loop.

**Comment by bezlant** [comment]
Another example of a bug. (Don't mind the 11111111 in res128, I have fixed it) 
The all zeroes value after our div is the concern.

<img width="1103" alt="Screen Shot 2022-06-17 at 09 23 48" src="https://user-images.githubusercontent.com/89563512/174237991-a643c8eb-bdd5-4ab6-b4d6-8c14d371188e.png">

Another example of an infinite loop.

<img width="247" alt="Screen Shot 2022-06-17 at 09 27 09" src="https://user-images.githubusercontent.com/89563512/174238461-51db954d-ef74-4412-a97e-7ac50fb21498.png">

**Comment by bezlant** [comment]
This doesn't cause a loop, but doesn't work.
<img width="1110" alt="Screen Shot 2022-06-17 at 09 28 19" src="https://user-images.githubusercontent.com/89563512/174238612-ee69e5a9-7511-46a5-ad9d-e2b133d25de9.png">

**Comment by bezlant** [comment]
More bugs
<img width="1111" alt="Screen Shot 2022-06-17 at 09 30 23" src="https://user-images.githubusercontent.com/89563512/174238916-381cbb7c-9720-4e7a-a118-41a310d2be93.png">

**Comment by bezlant** [comment]
Two negative values also gives us a bug with all zeroes.
<img width="1107" alt="Screen Shot 2022-06-17 at 09 29 45" src="https://user-images.githubusercontent.com/89563512/174238829-f57b47f6-fe9d-4c86-b607-722504ff478e.png">

**Comment by bezlant** [comment]
Both positive - WORKS!
<img width="1110" alt="Screen Shot 2022-06-17 at 09 30 48" src="https://user-images.githubusercontent.com/89563512/174238985-dc6381fa-e3e8-4dee-a6b9-bb7d3575f4a8.png">

**Comment by bezlant** [comment]
Floating point division doesn't work. (All zeroes)
<img width="1136" alt="Screen Shot 2022-06-17 at 09 37 51" src="https://user-images.githubusercontent.com/89563512/174240054-558ba525-bf0b-4a15-9372-07e5b16622dd.png">

**Comment by bezlant** [comment]
Works when both numbers are positive. (I know it does integer division)
<img width="1133" alt="Screen Shot 2022-06-17 at 09 38 39" src="https://user-images.githubusercontent.com/89563512/174240167-a9bae849-3bda-4a20-8c5a-a602868e1aa7.png">

**Comment by posidoni** [comment]
Thanks for reporting the bug, I will start working on this issue.

**Comment by bezlant** [comment]
Thank you for the hot fixes!
